# Generated by Django 5.1.4 on 2026-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_ended_at_event_external_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='recordings/incidents/'),
        ),
    ]
