# Generated by Django 5.1.4 on 2026-05-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='source',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
