# Generated by Django 5.1.4 on 2026-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
